# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "./dataset"
output_path: "./output"
load_path: "./output/checkpoint_path/"
device_target: "Ascend"
enable_profiling: False
dataset: 'kits19'
raw_data_path: './kits19'

# ==============================================================================
# Training options
model_name: "unet_simple"
include_background: False # True
run_eval: True
run_distribute: False
crop: None
image_size: [512, 512]
train_augment: True
lr: 0.0001
epochs: 50# 400
repeat: 1 
split: 0.8
distribute_epochs: 2400
batch_size: 16
cross_valid_ind: 1
num_classes: 3
num_channels: 1
weight_decay: 0.0005
loss_scale: 1024.0
FixedLossScaleManager: 1024.0
resume: False
resume_ckpt: "./"
transfer_training: False
filter_weight: ['final1.weight']
show_eval: False
color: [[0, 0, 0], [255, 0, 0], [0, 255, 0], [0, 0, 255], [0, 255, 255], [255, 0, 255], [255, 255, 255]]

#Eval options
eval_metrics: "dice_coeff"
eval_start_epoch: 0
eval_interval: 1
keep_checkpoint_max: 10
eval_activate: "Softmax"
eval_resize: False
checkpoint_path: "./checkpoint/"
checkpoint_file_path: "ckpt_unet_simple_adam-4-75.ckpt"
rst_path: "./result_Files/"
result_path: "./preprocess_Result"

# Export options
width: 512
height: 512
file_name: "unet"
file_format: "MINDIR"

# pred options
pred_save_path: './prediction'


---
# Help description for each configuration
enable_modelarts: "Whether training on modelarts, default: False"
data_url: "Dataset url for obs"
train_url: "Training output url for obs"
checkpoint_url: "The location of checkpoint for obs"
data_path: "Dataset path for local"
output_path: "Training output path for local"
load_path: "The location of checkpoint for obs"
device_target: "Target device type, available: [Ascend, GPU, CPU]"
enable_profiling: "Whether enable profiling while training, default: False"
num_classes: "Class for dataset"
batch_size: "Batch size for training and evaluation"
weight_decay: "Weight decay."
keep_checkpoint_max: "keep the last keep_checkpoint_max checkpoint"
checkpoint_path: "The location of the checkpoint file."
checkpoint_file_path: "The location of the checkpoint file."
train_augment: "Whether apply data augment when training."
